const inputsActionTypes = {
  CONTROLLER_CHANGE: 'CONTROLLER_CHANGE',
  INPUTCONFIG_SELECT_INPUT: 'INPUTCONFIG_SELECT_INPUT',
  INPUTCONFIG_RENAME: 'INPUTCONFIG_RENAME',
  INPUTCONFIG_RENAME_SHORT: 'INPUTCONFIG_RENAME_SHORT'
}

export default inputsActionTypes;