const inputsActionTypes = {
  CONTROLLER_CHANGE: 'CONTROLLER_CHANGE',
  INPUTCONFIG_SELECT_INPUT: 'INPUTCONFIG_SELECT_INPUT',
  INPUTCONFIG_RENAME: 'INPUTCONFIG_RENAME',
  INPUTCONFIG_RENAME_SHORT: 'INPUTCONFIG_RENAME_SHORT',
  INPUTCONFIG_UPDATE_FIELD: 'INPUTCONFIG_UPDATE_FIELD',
  INPUTCONFIG_DELETE_OPTION: 'INPUTCONFIG_DELETE_OPTION',
  INPUTCONFIG_NEW_OPTION: 'INPUTCONFIG_NEW_OPTION',
  INPUTCONFIG_SPREAD_OPTIONS_VALUES: 'INPUTCONFIG_SPREAD_OPTIONS_VALUES',
  INPUTCONFIG_SPREAD_OPTIONS_VALUES_MIDI: 'INPUTCONFIG_SPREAD_OPTIONS_VALUES_MIDI'
}

export default inputsActionTypes;