const inputsActionTypes = {
  CONTROLLER_CHANGE: 'CONTROLLER_CHANGE',
  INPUTCONFIG_SELECT_INPUT: 'INPUTCONFIG_SELECT_INPUT',
  INPUTCONFIG_RENAME: 'INPUTCONFIG_RENAME',
  INPUTCONFIG_RENAME_SHORT: 'INPUTCONFIG_RENAME_SHORT',
  INPUTCONFIG_UPDATE_FIELD: 'INPUTCONFIG_UPDATE_FIELD',
  INPUTCONFIG_UPDATE_MIDI_RECEIVE_STATUS: 'INPUTCONFIG_UPDATE_MIDI_RECEIVE_STATUS',
  INPUTCONFIG_UPDATE_MIDI_RECEIVE_DATA_1: 'INPUTCONFIG_UPDATE_MIDI_RECEIVE_DATA_1',
  INPUTCONFIG_UPDATE_MIDI_RECEIVE_HIRES: 'INPUTCONFIG_UPDATE_MIDI_RECEIVE_HIRES',
  INPUTCONFIG_UPDATE_MIDI_TRANSMIT_STATUS: 'INPUTCONFIG_UPDATE_MIDI_TRANSMIT_STATUS',
  INPUTCONFIG_UPDATE_MIDI_TRANSMIT_DATA_1: 'INPUTCONFIG_UPDATE_MIDI_TRANSMIT_DATA_1',
  INPUTCONFIG_UPDATE_MIDI_TRANSMIT_HIRES: 'INPUTCONFIG_UPDATE_MIDI_TRANSMIT_HIRES'  
}

export default inputsActionTypes;