#ifndef _MIDI_CONTROLLER_NUMBERS_H
#define _MIDI_CONTROLLER_NUMBERS_H

#define CC_BANK_SELECT 0x00
#define CC_MOD_WHEEL 0x01
#define CC_BREATH_CONTROLLER 0x02
#define CC_FOOT_CONTROLLER 0x04
#define CC_PORTAMENTO_TIME 0x05
#define CC_DATA_ENTRY_MSB 0x06
#define CC_CHANNEL_VOLUME 0x07
#define CC_BALANCE 0x08
#define CC_PAN 0x0A
#define CC_EXPRESSION_CONTROLLER 0x0A
#define CC_FX_CONTROL_1 0x0C
#define CC_FX_CONTROL_2 0x0D
#define CC_GENERAL_PURPOSE_1 0x10
#define CC_GENERAL_PURPOSE_2 0x11
#define CC_GENERAL_PURPOSE_3 0x12
#define CC_GENERAL_PURPOSE_4 0x13

#define CC_MOD_WHEEL_LSB 0x21
#define CC_BREATH_CONTROLLER_LSB 0x22
#define CC_FOOT_CONTROLLER_LSB 0x24
#define CC_PORTAMENTO_TIME_LSB 0x25
#define CC_DATA_ENTRY_LSB 0x26
#define CC_MAIN_VOLUME_LSB 0x27
#define CC_BALANCE_LSB 0x28
#define CC_PAN_LSB 0x2A
#define CC_FX_CONTROL_1_LSB 0x2C
#define CC_FX_CONTROL_2_LSB 0x2D
#define CC_GENERAL_PURPOSE_1_LSB 0x30
#define CC_GENERAL_PURPOSE_2_LSB 0x31
#define CC_GENERAL_PURPOSE_3_LSB 0x32
#define CC_GENERAL_PURPOSE_4_LSB 0x33

#define CC_SUSTAIN 0x40
#define CC_PORTAMENTO 0x41
#define CC_SOSTENUTO 0x42
#define CC_SOFT_PEDAL 0x43
#define CC_LEGATO_FOOTSWITCH 0x44
#define CC_HOLD_2 0x45
#define CC_SOUND_CONTROLLER_1 0x46
#define CC_SOUND_CONTROLLER_2 0x47
#define CC_SOUND_CONTROLLER_3 0x48
#define CC_SOUND_CONTROLLER_4 0x49
#define CC_SOUND_CONTROLLER_5 0x4A
#define CC_SOUND_CONTROLLER_6 0x4B
#define CC_SOUND_CONTROLLER_7 0x4C
#define CC_SOUND_CONTROLLER_8 0x4D
#define CC_SOUND_CONTROLLER_9 0x4E
#define CC_SOUND_CONTROLLER_10 0x4F
#define CC_GENERAL_PURPOSE_5 0x50
#define CC_GENERAL_PURPOSE_6 0x51
#define CC_GENERAL_PURPOSE_7 0x52
#define CC_GENERAL_PURPOSE_8 0x53
#define CC_PORTAMENTO_CONTROL 0x54
#define CC_HIGH_RES_VELOCITY_PREFIX 0x58
#define CC_FX_1_DEPTH 0x5B
#define CC_FX_2_DEPTH 0x5C
#define CC_FX_3_DEPTH 0x5D
#define CC_FX_4_DEPTH 0x5E
#define CC_FX_5_DEPTH 0x5F
#define CC_DATA_INC 0x60
#define CC_DATA_DEC 0x61
#define CC_NON_REG_PARAM_NUMBER_LSB 0x62
#define CC_NON_REG_PARAM_NUMBER_MSB 0x63
#define CC_REG_PARAM_NUMBER_LSB 0x64
#define CC_REG_PARAM_NUMBER_MSB 0x65

// Channel mode messages - see spec for tresholds etc
#define CC_ALL_SOUND_OFF 0x78
#define CC_RESET_ALL_CONTROLLERS 0x79
#define CC_LOCAL_CONTROL 0x7A
#define CC_ALL_NOTES_OFF 0x7B
#define CC_OMNI_OFF 0x7C
#define CC_OMNI_ON 0x7D
#define CC_MONO_ON 0x7E
#define CC_POLY_ON 0x7F

#endif