#ifndef _NODETYPES_H
#define _NODETYPES_H

// functions
#define NODE_INVERT 1
#define NODE_INVERT_EACH_SIDE 2
#define NODE_RAMP 3
#define NODE_DELAY_LINE 4
#define NODE_MULTIPLY 5
#define NODE_MEMORY 6
#define NODE_LFO_PULSE 7
#define NODE_SWITCH 8
#define NODE_COMPARE 9
#define NODE_MAX 10
#define NODE_MIN 11
#define NODE_SCALE 12
#define NODE_TRIGGER 13
#define NODE_BINARY_AND 14
#define NODE_BINARY_OR 15
#define NODE_BINARY_XOR 16
#define NODE_BINARY_NOT 17
#define NODE_BUFFER_INPUT 18
#define NODE_OUTPUT 19
#define NODE_OUTPUT_TUNED 20
#define NODE_GLIDE 21
#define NODE_QUANTIZE 22
#define NODE_POSITIVE_EXP 23
#define NODE_SUM 24
#define NODE_TUNE 25
#endif